version: "3.7"
services:
  bot:
    image: ghcr.io/yoki-labs/starboard/bot:latest
    container_name: GSTARBOARD_BOT
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - main-network
    depends_on:
      - cache
  cache:
    image: redis:latest
    container_name: GSTARBOARD_CACHE
    restart: unless-stopped
    networks:
      - main-network
    ports:
      - "6380:6380"
    command: redis-server --port 6380
    volumes: 
      - redis-data:/data

networks:
  main-network:
    driver: bridge

volumes:
  redis-data: