name: Build Image
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "src/**"

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up QEMU
              if: steps.verify-changed-files.outputs.service == 'true'
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              if: steps.verify-changed-files.outputs.service == 'true'
              uses: docker/setup-buildx-action@v2

            - name: Login to GCR
              if: steps.verify-changed-files.outputs.service == 'true'
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              if: steps.verify-changed-files.outputs.service == 'true'
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: ghcr.io/${{ github.repository }}/bot:latest
                  file: Dockerfile